hyperparameters:
  NFOLD: 5
  truncate_last_timesteps: 4096
  num_class: 2
  batch_size: 32
  training_epochs: 30
  training_steps_per_epoch: 500
  shuffle_buffer: 1024
model:
  architecture_name: conv_mhsa
  input_shape: [4096, 23]
augment:
  random_shift:
    backward: 64
    forward: 64
environment:
  type: colab_tpu

